# .github/workflows/python-app.yml
name: Flask Blog CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --exclude=venv --max-line-length=100

    - name: Run tests
      env:
        FLASK_KEY: test_secret_key
        DB_URI: sqlite:///test.db
      run: |
        pip install pytest
        pytest tests/
